# Generated by Django 3.0 on 2020-03-13 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
        ('inventory', '0003_campitem_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campitem',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.CampingTrip'),
        ),
        migrations.DeleteModel(
            name='CampingTrip',
        ),
    ]
